const mockedGloberBiosRepo = {
    data: [
        {
            id: '1',
            email: 'alan.zambrano@globant.com',
            career: 'Career Summary',
            programming: 'JS, C#, Other',
            jsFrameworks: 'jQuery, ReactJS',
            databases: 'SQL Server, MongoDB',
            mvcFrameworkds: 'Angular, ASP.NET',
            presentation: 'Hello',
            mobile: 'Objective-C',
            bigData: 'R',
            testing: 'xUnit, Jest',
            other: 'Other',
            tools: 'YouTrack, PyCharm',
            english: 'Advanced',
            spanish: 'Native',
            portuguese: 'No',
            otherlanguages: 'No',
            ts: new Date()
        }, {
            id: '2',
            email: 'bruno.guardia@globant.com',
            career: 'Career Summary',
            programming: 'JS, C#, Other',
            jsFrameworks: 'jQuery, ReactJS',
            databases: 'SQL Server, MongoDB',
            mvcFrameworkds: 'Angular, ASP.NET',
            presentation: 'Hello',
            mobile: 'Objective-C',
            bigData: 'R',
            testing: 'xUnit, Jest',
            other: 'Other',
            tools: 'YouTrack, PyCharm',
            english: 'Advanced',
            spanish: 'Native',
            portuguese: 'No',
            otherlanguages: 'No',
            ts: new Date()
        }, {
            id: '3',
            email: 'jose.valencia@globant.com',
            career: 'Career Summary',
            programming: 'JS, C#, Other',
            jsFrameworks: 'jQuery, ReactJS',
            databases: 'SQL Server, MongoDB',
            mvcFrameworkds: 'Angular, ASP.NET',
            presentation: 'Hello',
            mobile: 'Objective-C',
            bigData: 'R',
            testing: 'xUnit, Jest',
            other: 'Other',
            tools: 'YouTrack, PyCharm',
            english: 'Advanced',
            spanish: 'Native',
            portuguese: 'No',
            otherlanguages: 'No',
            ts: new Date()
        }, {
            id: '4',
            email: 'sofia.galan@globant.com',
            career: 'Career Summary',
            programming: 'JS, C#, Other',
            jsFrameworks: 'jQuery, ReactJS',
            databases: 'SQL Server, MongoDB',
            mvcFrameworkds: 'Angular, ASP.NET',
            presentation: 'Hello',
            mobile: 'Objective-C',
            bigData: 'R',
            testing: 'xUnit, Jest',
            other: 'Other',
            tools: 'YouTrack, PyCharm',
            english: 'Advanced',
            spanish: 'Native',
            portuguese: 'No',
            otherlanguages: 'No',
            ts: new Date()
        }, {
            id: '5',
            email: 'lucia.echenique@globant.com',
            career: 'Career Summary',
            programming: 'JS, C#, Other',
            jsFrameworks: 'jQuery, ReactJS',
            databases: 'SQL Server, MongoDB',
            mvcFrameworkds: 'Angular, ASP.NET',
            presentation: 'Hello',
            mobile: 'Objective-C',
            bigData: 'R',
            testing: 'xUnit, Jest',
            other: 'Other',
            tools: 'YouTrack, PyCharm',
            english: 'Advanced',
            spanish: 'Native',
            portuguese: 'No',
            otherlanguages: 'No',
            ts: new Date()
        }
    ],
    getDataByEmail: function (metaData, email) {
        return mockedGloberBiosRepo.data.find((element) => element.email === email);
    }
};

module.exports = mockedGloberBiosRepo;